""""
This sample shows how to write MacroFlo data
"""

import iesve    # the VE api

# # MAIN BODY STARTS HERE # #
if __name__ == '__main__':   
    project = iesve.VEProject.get_current_project()
    opening_types = project.get_macro_flo_opening_types()

    for opening in opening_types:
        opening.set({'crack_flow_coefficient': 0.15,
                     'crack_length': 10,
                     'description': 'Generated by Python',
                     'equivalent_orifice_area': 0.0,
                     'exposure_type': '06. semi-exposed roof <10deg',
                     'openable_area': 0.0,
                     'opening_category': iesve.opening_type.custom_sharp_edge_orifice,
                     'opening_threshold': 18.0,
                     'profile': 'OFF'})